# Generated by Django 6.0.6 on 2026-06-06 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True, verbose_name='ID из opendata')),
                ('number', models.CharField(max_length=10, verbose_name='Номер маршрута')),
                ('name', models.CharField(max_length=255, verbose_name='Название маршрута')),
                ('transport_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип транспорта')),
                ('direction', models.CharField(choices=[('A-B', 'Прямое направление'), ('B-A', 'Обратное направление')], default='A-B', max_length=5, verbose_name='Направление')),
                ('length_km', models.FloatField(blank=True, null=True, verbose_name='Длина маршрута (км)')),
                ('garage', models.CharField(blank=True, max_length=255, null=True, verbose_name='Гараж')),
                ('coordinates', models.JSONField(default=list, verbose_name='Координаты маршрута')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название остановки')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Остановка',
                'verbose_name_plural': 'Остановки',
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок остановки')),
                ('estimated_time', models.PositiveIntegerField(default=0, verbose_name='Время от начала маршрута (мин)')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='routes.route', verbose_name='Маршрут')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='routes.stop', verbose_name='Остановка')),
            ],
            options={
                'verbose_name': 'Остановка маршрута',
                'verbose_name_plural': 'Остановки маршрута',
                'ordering': ['order'],
            },
        ),
    ]
