# Generated by Django 6.0.6 on 2026-06-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Отмечен'),
        ),
        migrations.AddField(
            model_name='route',
            name='vehicle_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество транспорта'),
        ),
        migrations.AddField(
            model_name='route',
            name='work_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец работы'),
        ),
        migrations.AddField(
            model_name='route',
            name='work_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало работы'),
        ),
        migrations.AlterField(
            model_name='route',
            name='coordinates',
            field=models.JSONField(default=list, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='route',
            name='length_km',
            field=models.FloatField(blank=True, null=True, verbose_name='Длина (км)'),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='estimated_time',
            field=models.PositiveIntegerField(default=0, verbose_name='Время от начала (мин)'),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Порядок'),
        ),
    ]
