# Generated by Django 6.0.6 on 2026-06-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_route_is_favorite_route_vehicle_count_route_work_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='avg_trip_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Среднее время рейса (мин)'),
        ),
        migrations.AddField(
            model_name='route',
            name='bus_brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Марка автобуса'),
        ),
        migrations.AlterField(
            model_name='route',
            name='garage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Автопарк'),
        ),
        migrations.AlterField(
            model_name='route',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Избранный'),
        ),
    ]
