# Generated by Django 6.0.6 on 2026-06-06 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetroLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название линии')),
                ('color', models.CharField(default='#FF0000', max_length=7, verbose_name='Цвет линии (HEX)')),
            ],
            options={
                'verbose_name': 'Линия метро',
                'verbose_name_plural': 'Линии метро',
            },
        ),
        migrations.CreateModel(
            name='MetroStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название станции')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок на линии')),
                ('interval_minutes', models.PositiveIntegerField(default=5, verbose_name='Интервал движения (мин)')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='metro.metroline', verbose_name='Линия')),
            ],
            options={
                'verbose_name': 'Станция метро',
                'verbose_name_plural': 'Станции метро',
                'ordering': ['order'],
            },
        ),
    ]
