# Generated by Django 6.0.6 on 2026-06-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metroline',
            name='waypoints',
            field=models.JSONField(blank=True, default=list, verbose_name='Промежуточные точки маршрута'),
        ),
    ]
